const categories=[
 {id:"italian",name:"Italian"},
 {id:"chinese",name:"Chinese"},
 {id:"japanese",name:"Japanese"},
 {id:"panda",name:"Panda Express"},
 {id:"taco",name:"Taco Bell"},
 {id:"mcdonalds",name:"McDonald's"},
 {id:"desserts",name:"Desserts"},
 {id:"beverages",name:"Beverages"},
 {id:"uzbek",name:"Uzbek Traditional"},
 {id:"seafood",name:"Sea Food"},
 {id:"icecream",name:"Ice Creams"},
 {id:"combos",name:"Combos"},
 {id:"assorti",name:"Assortis"},
 {id:"royal",name:"Royal Foods"},
 {id:"steak",name:"Steaks"},
 {id:"special",name:"Specials"}
];

const foods=[

/* ITALIAN */
{id:1,name:"Margherita Pizza",cat:"italian",img:"assets/foods/italian_1.avif"},
{id:2,name:"Pepperoni Pizza",cat:"italian",img:"assets/foods/italian_2.jpg"},
{id:3,name:"Four Cheese Pizza",cat:"italian",img:"assets/foods/italian_3.jpg"},
{id:4,name:"Carbonara Pasta",cat:"italian",img:"assets/foods/italian_4.jpg"},
{id:5,name:"Lasagna",cat:"italian",img:"assets/foods/italian_5.jpg"},
{id:6,name:"Fettuccine Alfredo",cat:"italian",img:"assets/foods/italian_6.jpg"},
{id:7,name:"Ravioli",cat:"italian",img:"assets/foods/italian_7.jpg"},
{id:8,name:"Risotto",cat:"italian",img:"assets/foods/italian_8.jpg"},
{id:9,name:"Calzone",cat:"italian",img:"assets/foods/italian_9.jpg"},
{id:10,name:"Bruschetta",cat:"italian",img:"assets/foods/italian_10.jpg"},

/* CHINESE */
{id:11,name:"Kung Pao Chicken",cat:"chinese",img:"assets/foods/chinese_1.jpg"},
{id:12,name:"Sweet and Sour Chicken",cat:"chinese",img:"assets/foods/chinese_2.jpg"},
{id:13,name:"Fried Rice",cat:"chinese",img:"assets/foods/chinese_3.jpg"},
{id:14,name:"Chow Mein",cat:"chinese",img:"assets/foods/chinese_4.jpg"},
{id:15,name:"Lo Mein",cat:"chinese",img:"assets/foods/chinese_5.jpg"},
{id:16,name:"Spring Rolls",cat:"chinese",img:"assets/foods/chinese_6.jpg"},
{id:17,name:"Dumplings",cat:"chinese",img:"assets/foods/chinese_7.jpg"},
{id:18,name:"Mapo Tofu",cat:"chinese",img:"assets/foods/chinese_8.jpg"},
{id:19,name:"Hot Pot",cat:"chinese",img:"assets/foods/chinese_9.jpg"},
{id:20,name:"Peking Duck",cat:"chinese",img:"assets/foods/chinese_10.jpg"},

/* JAPANESE */
{id:21,name:"Sushi Roll",cat:"japanese",img:"assets/foods/japanese_1.jpg"},
{id:22,name:"Ramen",cat:"japanese",img:"assets/foods/japanese_2.jpg"},
{id:23,name:"Tempura",cat:"japanese",img:"assets/foods/japanese_3.jpg"},
{id:24,name:"Udon Noodles",cat:"japanese",img:"assets/foods/japanese_4.jpg"},
{id:25,name:"Takoyaki",cat:"japanese",img:"assets/foods/japanese_5.jpg"},
{id:26,name:"Okonomiyaki",cat:"japanese",img:"assets/foods/japanese_6.jpg"},
{id:27,name:"Sashimi",cat:"japanese",img:"assets/foods/japanese_7.jpg"},
{id:28,name:"Onigiri",cat:"japanese",img:"assets/foods/japanese_8.jpg"},
{id:29,name:"Chicken Katsu",cat:"japanese",img:"assets/foods/japanese_9.jpg"},
{id:30,name:"Miso Soup",cat:"japanese",img:"assets/foods/japanese_10.jpg"},

/* PANDA EXPRESS */
{id:31,name:"Orange Chicken",cat:"panda",img:"assets/foods/panda_1.jpg"},
{id:32,name:"Beijing Beef",cat:"panda",img:"assets/foods/panda_2.jpg"},
{id:33,name:"Broccoli Beef",cat:"panda",img:"assets/foods/panda_3.jpg"},
{id:34,name:"Honey Walnut Shrimp",cat:"panda",img:"assets/foods/panda_4.jpg"},
{id:35,name:"Kung Pao Chicken",cat:"panda",img:"assets/foods/panda_5.jpg"},
{id:36,name:"Teriyaki Chicken",cat:"panda",img:"assets/foods/panda_6.jpg"},
{id:37,name:"Chow Mein",cat:"panda",img:"assets/foods/panda_7.jpg"},
{id:38,name:"Fried Rice",cat:"panda",img:"assets/foods/panda_8.jpg"},
{id:39,name:"Egg Rolls",cat:"panda",img:"assets/foods/panda_9.jpg"},
{id:40,name:"Apple Pie Roll",cat:"panda",img:"assets/foods/panda_10.jpg"},

/* TACO BELL */
{id:41,name:"Crunchy Taco",cat:"taco",img:"assets/foods/taco_1.jpg"},
{id:42,name:"Soft Taco",cat:"taco",img:"assets/foods/taco_2.jpg"},
{id:43,name:"Beef Burrito",cat:"taco",img:"assets/foods/taco_3.jpg"},
{id:44,name:"Chicken Quesadilla",cat:"taco",img:"assets/foods/taco_4.jpg"},
{id:45,name:"Crunchwrap Supreme",cat:"taco",img:"assets/foods/taco_5.jpg"},
{id:46,name:"Nachos BellGrande",cat:"taco",img:"assets/foods/taco_6.jpg"},
{id:47,name:"Doritos Locos Taco",cat:"taco",img:"assets/foods/taco_7.jpg"},
{id:48,name:"Cheesy Roll Up",cat:"taco",img:"assets/foods/taco_8.jpg"},
{id:49,name:"Mexican Pizza",cat:"taco",img:"assets/foods/taco_9.jpg"},
{id:50,name:"Loaded Fries",cat:"taco",img:"assets/foods/taco_10.jpg"},

/* MCDONALDS */
{id:51,name:"Big Mac",cat:"mcdonalds",img:"assets/foods/mcd_1.avif"},
{id:52,name:"Quarter Pounder",cat:"mcdonalds",img:"assets/foods/mcd_2.jpg"},
{id:53,name:"McChicken",cat:"mcdonalds",img:"assets/foods/mcd_3.jpg"},
{id:54,name:"Double Cheeseburger",cat:"mcdonalds",img:"assets/foods/mcd_4.jpg"},
{id:55,name:"McNuggets",cat:"mcdonalds",img:"assets/foods/mcd_5.jpg"},
{id:56,name:"Filet-O-Fish",cat:"mcdonalds",img:"assets/foods/mcd_6.jpg"},
{id:57,name:"French Fries",cat:"mcdonalds",img:"assets/foods/mcd_7.jpg"},
{id:58,name:"McFlurry",cat:"mcdonalds",img:"assets/foods/mcd_8.jpg"},
{id:59,name:"Apple Pie",cat:"mcdonalds",img:"assets/foods/mcd_9.jpg"},
{id:60,name:"Sausage McMuffin",cat:"mcdonalds",img:"assets/foods/mcd_10.avif"},

/* DESSERTS */
{id:61,name:"Chocolate Cake",cat:"desserts",img:"assets/foods/desserts_1.jpg"},
{id:62,name:"Cheesecake",cat:"desserts",img:"assets/foods/desserts_2.webp"},
{id:63,name:"Brownie",cat:"desserts",img:"assets/foods/desserts_3.jpg"},
{id:64,name:"Tiramisu",cat:"desserts",img:"assets/foods/desserts_4.jpg"},
{id:65,name:"Apple Pie",cat:"desserts",img:"assets/foods/desserts_5.jpg"},
{id:66,name:"Donuts",cat:"desserts",img:"assets/foods/desserts_6.jpg"},
{id:67,name:"Cupcakes",cat:"desserts",img:"assets/foods/desserts_7.jpg"},
{id:68,name:"Macarons",cat:"desserts",img:"assets/foods/desserts_8.jpg"},
{id:69,name:"Pancakes",cat:"desserts",img:"assets/foods/desserts_9.avif"},
{id:70,name:"Waffles",cat:"desserts",img:"assets/foods/desserts_10.avif"},

/* BEVERAGES */
{id:71,name:"Cola",cat:"beverages",img:"assets/foods/beverages_1.webp"},
{id:72,name:"Orange Juice",cat:"beverages",img:"assets/foods/beverages_2.jpg"},
{id:73,name:"Lemonade",cat:"beverages",img:"assets/foods/beverages_3.avif"},
{id:74,name:"Milkshake",cat:"beverages",img:"assets/foods/beverages_4.jpg"},
{id:75,name:"Iced Coffee",cat:"beverages",img:"assets/foods/beverages_5.webp"},
{id:76,name:"Hot Coffee",cat:"beverages",img:"assets/foods/beverages_6.jpg"},
{id:77,name:"Green Tea",cat:"beverages",img:"assets/foods/beverages_7.jpg"},
{id:78,name:"Black Tea",cat:"beverages",img:"assets/foods/beverages_8.png"},
{id:79,name:"Energy Drink",cat:"beverages",img:"assets/foods/beverages_9.jpg"},
{id:80,name:"Mineral Water",cat:"beverages",img:"assets/foods/beverages_10.webp"},

/* UZBEK TRADITIONAL */
{id:81,name:"Somsa",cat:"uzbek",img:"assets/foods/uzbek_1.avif"},
{id:82,name:"Tandir Somsa",cat:"uzbek",img:"assets/foods/uzbek_2.jpg"},
{id:83,name:"Shashlik Kuskavoy",cat:"uzbek",img:"assets/foods/uzbek_3.jpg"},
{id:84,name:"Shashlik Kofta",cat:"uzbek",img:"assets/foods/uzbek_4.webp"},
{id:85,name:"Plov",cat:"uzbek",img:"assets/foods/uzbek_5.jpg"},
{id:86,name:"Manti",cat:"uzbek",img:"assets/foods/uzbek_6.avif"},
{id:87,name:"Lagman",cat:"uzbek",img:"assets/foods/uzbek_7.webp"},
{id:88,name:"Norin",cat:"uzbek",img:"assets/foods/uzbek_8.jpg"},
{id:89,name:"Chuchvara",cat:"uzbek",img:"assets/foods/uzbek_9.jpg"},
{id:90,name:"Kazan Kebab",cat:"uzbek",img:"assets/foods/uzbek_10.jpg"},

/* SEA FOOD */
{id:91,name:"Grilled Salmon",cat:"seafood",img:"assets/foods/seafood_1.jpg"},
{id:92,name:"Fried Shrimp",cat:"seafood",img:"assets/foods/seafood_2.jpg"},
{id:93,name:"Fish and Chips",cat:"seafood",img:"assets/foods/seafood_3.avif"},
{id:94,name:"Crab Legs",cat:"seafood",img:"assets/foods/seafood_4.jpg"},
{id:95,name:"Lobster Tail",cat:"seafood",img:"assets/foods/seafood_5.jpg"},
{id:96,name:"Grilled Tuna",cat:"seafood",img:"assets/foods/seafood_6.jpg"},
{id:97,name:"Seafood Pasta",cat:"seafood",img:"assets/foods/seafood_7.webp"},
{id:98,name:"Shrimp Cocktail",cat:"seafood",img:"assets/foods/seafood_8.jpg"},
{id:99,name:"Fish Soup",cat:"seafood",img:"assets/foods/seafood_9.jpeg"},
{id:100,name:"Calamari",cat:"seafood",img:"assets/foods/seafood_10.webp"},

/* ICE CREAMS */
{id:101,name:"Vanilla Ice Cream",cat:"icecream",img:"assets/foods/icecream_1.webp"},
{id:102,name:"Chocolate Ice Cream",cat:"icecream",img:"assets/foods/icecream_2.jpg"},
{id:103,name:"Strawberry Ice Cream",cat:"icecream",img:"assets/foods/icecream_3.jpg"},
{id:104,name:"Mint Ice Cream",cat:"icecream",img:"assets/foods/icecream_4.jpg"},
{id:105,name:"Cookies and Cream",cat:"icecream",img:"assets/foods/icecream_5.jpg"},
{id:106,name:"Mango Ice Cream",cat:"icecream",img:"assets/foods/icecream_6.jpg"},
{id:107,name:"Pistachio Ice Cream",cat:"icecream",img:"assets/foods/icecream_7.jpg"},
{id:108,name:"Caramel Ice Cream",cat:"icecream",img:"assets/foods/icecream_8.jpg"},
{id:109,name:"Banana Split",cat:"icecream",img:"assets/foods/icecream_9.jpg"},
{id:110,name:"Ice Cream Sundae",cat:"icecream",img:"assets/foods/icecream_10.jpg"},

/* COMBOS */
{id:111,name:"Burger Combo",cat:"combos",img:"assets/foods/combos_1.webp"},
{id:112,name:"Pizza Combo",cat:"combos",img:"assets/foods/combos_2.avif"},
{id:113,name:"Family Meal Combo",cat:"combos",img:"assets/foods/combos_3.webp"},
{id:114,name:"Chicken Combo",cat:"combos",img:"assets/foods/combos_4.jpg"},
{id:115,name:"Kids Combo",cat:"combos",img:"assets/foods/combos_5.avif"},
{id:116,name:"Snack Combo",cat:"combos",img:"assets/foods/combos_6.jpg"},
{id:117,name:"Seafood Combo",cat:"combos",img:"assets/foods/combos_7.jpg"},
{id:118,name:"Taco Combo",cat:"combos",img:"assets/foods/combos_8.jpg"},
{id:119,name:"Dessert Combo",cat:"combos",img:"assets/foods/combos_9.jpg"},
{id:120,name:"Breakfast Combo",cat:"combos",img:"assets/foods/combos_10.webp"},

/* ASSORTIS */
{id:121,name:"Qazi Assorti",cat:"assorti",img:"assets/foods/assorti_1.avif"},
{id:122,name:"Chicken Assorti",cat:"assorti",img:"assets/foods/assorti_2.jpg"},
{id:123,name:"Seafood Assorti",cat:"assorti",img:"assets/foods/assorti_3.jpg"},
{id:124,name:"Vegetable Assorti",cat:"assorti",img:"assets/foods/assorti_4.webp"},
{id:125,name:"Snack Assorti",cat:"assorti",img:"assets/foods/assorti_5.jpg"},
{id:126,name:"Grill Assorti",cat:"assorti",img:"assets/foods/assorti_6.jpg"},
{id:127,name:"BBQ Assorti",cat:"assorti",img:"assets/foods/assorti_7.jpg"},
{id:128,name:"Cheese Assorti",cat:"assorti",img:"assets/foods/assorti_8.jpg"},
{id:129,name:"Fruit Assorti",cat:"assorti",img:"assets/foods/assorti_9.jpg"},
{id:130,name:"Party Assorti",cat:"assorti",img:"assets/foods/assorti_10.jpg"},

/* ROYAL FOODS */
{id:131,name:"Royal Platter",cat:"royal",img:"assets/foods/royal_1.jpg"},
{id:132,name:"Golden Steak",cat:"royal",img:"assets/foods/royal_2.webp"},
{id:133,name:"Luxury Seafood Plate",cat:"royal",img:"assets/foods/royal_3.jpeg"},
{id:134,name:"Royal Grill Mix",cat:"royal",img:"assets/foods/royal_4.jpg"},
{id:135,name:"Premium Lamb Rack",cat:"royal",img:"assets/foods/royal_5.jpg"},
{id:136,name:"Royal Chicken Roast",cat:"royal",img:"assets/foods/royal_6.jpg"},
{id:137,name:"King’s Burger",cat:"royal",img:"assets/foods/royal_7.jpg"},
{id:138,name:"Royal Dessert Plate",cat:"royal",img:"assets/foods/royal_8.jpg"},
{id:139,name:"Chef Special Royal",cat:"royal",img:"assets/foods/royal_9.webp"},
{id:140,name:"Diamond Platter",cat:"royal",img:"assets/foods/royal_10.jpg"},

/* STEAKS */
{id:141,name:"Ribeye Steak",cat:"steak",img:"assets/foods/steak_1.jpg"},
{id:142,name:"T-Bone Steak",cat:"steak",img:"assets/foods/steak_2.webp"},
{id:143,name:"Sirloin Steak",cat:"steak",img:"assets/foods/steak_3.jpg"},
{id:144,name:"Tenderloin Steak",cat:"steak",img:"assets/foods/steak_4.jpg"},
{id:145,name:"Porterhouse Steak",cat:"steak",img:"assets/foods/steak_5.jpg"},
{id:146,name:"Grilled Beef Steak",cat:"steak",img:"assets/foods/steak_6.png"},
{id:147,name:"Pepper Steak",cat:"steak",img:"assets/foods/steak_7.jpg"},
{id:148,name:"Garlic Butter Steak",cat:"steak",img:"assets/foods/steak_8.jpg"},
{id:149,name:"BBQ Steak",cat:"steak",img:"assets/foods/steak_9.jpg"},
{id:150,name:"Classic Beef Steak",cat:"steak",img:"assets/foods/steak_10.jpg"},

/* SPECIALS */
{id:151,name:"Chef Special Burger",cat:"special",img:"assets/foods/special_1.webp"},
{id:152,name:"Limited Edition Pizza",cat:"special",img:"assets/foods/special_2.jpg"},
{id:153,name:"Seasonal Soup",cat:"special",img:"assets/foods/special_3.jpg"},
{id:154,name:"Special Fried Chicken",cat:"special",img:"assets/foods/special_4.jpg"},
{id:155,name:"Holiday Dessert",cat:"special",img:"assets/foods/special_5.jpg"},
{id:156,name:"Special Combo Meal",cat:"special",img:"assets/foods/special_6.webp"},
{id:157,name:"Chef’s Signature Steak",cat:"special",img:"assets/foods/special_7.jpg"},
{id:158,name:"Special Seafood Plate",cat:"special",img:"assets/foods/special_8.avif"},
{id:159,name:"Mystery Box Meal",cat:"special",img:"assets/foods/special_9.jpg"},
{id:160,name:"Ultimate Special Platter",cat:"special",img:"assets/foods/special_10.jpg"}

];
